### ISSUE TITLE
Doesn't handle interpolated

### ISSUE THREAD

**Issue by worthy7** [Tzahi12345/xliff-to-json#1]
My extracted xliff has this content, it causes an error.

```
<unit id="5437278623178104519">
      <segment>
        <source>
          <ph id="0" equiv="INTERPOLATION" disp="{{ caldata.calendarOptions.guestChoosesLocationQuestionText }}"/>
        </source>
      </segment>
    </unit>
```

**Comment by Tzahi12345** [comment]
What was the error you got?

Also a bit confused on the excerpt provided, is this just a source translation file? There's no target, I suppose you're looking for a json like this?

```
{
  "5437278623178104519": "{{ caldata.calendarOptions.guestChoosesLocationQuestionText }}"
}
```

There wasn't support for xliff 2.0, but I went ahead and fixed that: https://github.com/Tzahi12345/xliff-to-json/commit/5435e111b1cb1c290327acd4e6a59b786c6d6b39

**Comment by worthy7** [comment]
`.map` is not a function I think. I tried to fix it manually but I couldn't work it out. 
I used this version https://socket.dev/npm/package/@ni/xliff-to-json-converter that was forked from yours, it worked great.

**Comment by Tzahi12345** [comment]
Sounds great! Not sure it was forked from mine though :)

**Comment by worthy7** [comment]
Ah, I didn't read the name properly.
It would be good if all these xliff-to-json tools were combined into one. This whole Angular localization journey has been quite a pain 😂
Or maybe this package can be sunsetted and reference that new one?

**Comment by Tzahi12345** [comment]
I'll look into the one you linked, I actually original created this package to help with a separate project I have as I couldn't find an alternative, but if @ni/xliff-to-json-converter works without issue I'll just switch over.

>This whole Angular localization journey has been quite a pain 😂

Tell me about it. Imo there should be built in tools within Angular to do the conversion, considering JSON is natively supported.

Either way I'll consider adding a disclaimer mentioning that other package in the README. Thanks!
